### ISSUE TITLE
How can I do the spherical world from the GIF in the README file?

### ISSUE THREAD

**Issue by z3nth10n** [bbQsauce5/transvoxel-unity#1]
Hi,

I want to do the spherical world from the GIF in the README file: https://github.com/bbQsauce5/transvoxel-unity/tree/main#system-features

Could you upload or explain how to achieve that?

**Comment by bbQsauce5** [comment]
Hi, sorry for the late response.

The density function is handled by the GetValue function inside the DensityGenerator class.
To make a sphere, you can simply replace the code with the SDF of a sphere:

```
var voxelPos = new float3(x,y,z);
var spherePos = new float3(0,0,0);
var sphereRadius = 500.0f;
var sphereSdf = sphereRadius - math.dist(spherePos, voxelPos);
```

This will give you a perfect sphere SDF.
To add noise distortion, you can simply add the result of the noise function to the sphere SDF.

```
var sphereDistorted = sphereSdf + _noise3D.GetNoise(x, y, z) * _noise3DStrength;`
```

I typed the code right away so there might be some mistakes, but that's the gist of it.
For more information about SDFs and more distance functions visit IQ's article: https://iquilezles.org/articles/distfunctions/
